name: CI

on:
  push:
    branches:
      - '2.0'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  testsuite:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - uses: php-actions/composer@v6
        with:
          php_version: '8.0'

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v4
        env:
          TEST_NAME: Scarlett
        with:
          php_version: '8.0'
          version: '8.5'
          coverage_clover: coverage.xml

  cs-stan:
    name: Coding Standard & Static Analysis
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: mbstring, intl
        coverage: none
        tools: phive, cs2pr

    - name: Composer install
      run: composer update

    - name: Run phpcs
      if: always()
      run: vendor/bin/phpcs --report=checkstyle src/ tests/ | cs2pr
